sudo: required

language: node_js

services:
  - docker

node_js: 10

cache: yarn

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - docker swarm init

after_success:
  - yarn coveralls
